### PR TITLE
Add Bower compatibility

### PR DESCRIPTION
**Pull request by siamkreative**
Bower is a package manager for the web and this awesome money.js deserves to be found via Bower...

### CODE REVIEW

**Comment by LinoleumKnife** [comment]
If this doesn't get merged in, you can get money.js with bower using:

bower install git://github.com/openexchangerates/money.js --save

**Comment by siamkreative** [comment]
@AndrewDapkiewicz is correct. Would be great if it could be merged though...

**Comment by fmartingr** [comment]
+1 for this.

As a note, if you do `bower install money` [this](https://github.com/josscrowcroft/money.js) repository get installed instead:

```
➜  Temp  bower install money
bower money#*               not-cached git://github.com/josscrowcroft/money.js.git#*
bower money#*                  resolve git://github.com/josscrowcroft/money.js.git#*
bower money#*                 download https://github.com/josscrowcroft/money.js/archive/0.1.3.tar.gz
bower money#*                  extract archive.tar.gz
bower money#*             invalid-meta money is missing "main" entry in bower.json
bower money#*             invalid-meta money is missing "ignore" entry in bower.json
bower money#*                 resolved git://github.com/josscrowcroft/money.js.git#0.1.3
bower money#~0.1.3             install money#0.1.3
```

**Comment by studio31** [comment]
+1

**Comment by masciugo** [comment]
+1

**Pull request closed without merging**
